/* =========================================================
 MA7ALAK LIVE CHAT V6 — MESSAGE ACCEPTANCE + SAFE CONVERSATION LOAD
 - keeps V5 avatars/unread/report/message acceptance
 - fixes conversation ID string/number mismatch
 - fixes duplicate chat shells causing opened conversations to stay on Loading
========================================================= */
(function(){
"use strict";if(window.__MA7ALAK_CHAT_V6__)return;window.__MA7ALAK_CHAT_V6__=true;
let client,user,mode="viewer",channel=null,settingsChannel=null;const sleep=m=>new Promise(r=>setTimeout(r,m)),esc=v=>String(v||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
async function vr(){for(let i=0;i<100&&!window.Ma7alakAccount;i++)await sleep(50);if(!window.Ma7alakAccount)throw new Error("Ma7alak account system is not ready.");await window.Ma7alakAccount.ready();client=window.Ma7alakAccount.client;user=window.Ma7alakAccount.user;mode="viewer"}
async function or(){for(let i=0;i<100&&!window.Ma7alakOwnerAuth;i++)await sleep(50);if(!window.Ma7alakOwnerAuth)throw new Error("Ma7alak owner system is not ready.");await window.Ma7alakOwnerAuth.ready();client=window.Ma7alakOwnerAuth.client;user=window.Ma7alakOwnerAuth.user;mode="owner";return !!window.Ma7alakOwnerAuth.owner}
function css(){if(document.getElementById("m7c-v6-css"))return;let s=document.createElement("style");s.id="m7c-v6-css";s.textContent=`#m7-chat-shell{position:fixed;inset:0;background:#000b;z-index:2147483500;display:flex;align-items:flex-end;justify-content:center;font-family:Arial}#m7-chat{width:min(540px,100%);height:min(760px,92vh);background:#100e0d;color:#fff;border:1px solid #db9b4659;border-radius:24px 24px 0 0;display:flex;flex-direction:column;overflow:hidden}#m7-chat-head{padding:12px 14px;background:#1d1511;border-bottom:1px solid #3b2a20;display:flex;align-items:center;gap:8px}.m7-head-person{display:flex;align-items:center;gap:9px;min-width:0;flex:1}.m7-avatar{width:40px;height:40px;border-radius:50%;object-fit:cover;border:2px solid #d99a45;background:#30251f}.m7-avatar.fallback{display:grid;place-items:center;font-weight:900;color:#f1b45a}#m7-chat-title{font-weight:900;color:#f1b45a;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.m7c-icon{border:0;background:#30251f;color:#fff;border-radius:10px;padding:8px 10px;cursor:pointer}#m7-owner-accept{border:1px solid #ffffff18;border-radius:10px;padding:8px 9px;font:800 10px Arial;cursor:pointer;white-space:nowrap}#m7-owner-accept.on{background:#24452e;color:#bff1cb}#m7-owner-accept.off{background:#522b27;color:#ffd0ca}#m7-chat-body{flex:1;overflow:auto;padding:14px;display:flex;flex-direction:column;gap:9px}.m7-msg{max-width:78%;padding:10px 12px;border-radius:16px;background:#29231f;line-height:1.35;word-break:break-word}.m7-msg.mine{align-self:flex-end;background:#a96d28}.m7-msg-time{font-size:10px;opacity:.6;margin-top:4px}#m7-chat-send{display:flex;gap:8px;padding:10px;background:#171310;border-top:1px solid #34261e}#m7-chat-input{flex:1;border:1px solid #453327;background:#0e0c0b;color:#fff;border-radius:14px;padding:12px}#m7-chat-send button{border:0;border-radius:14px;background:#d99a45;font-weight:900;padding:0 17px}.m7-convo{display:flex;align-items:center;gap:11px;padding:12px;border:1px solid #34281f;border-radius:16px;background:#191512;cursor:pointer;position:relative}.m7-convo.unread{border-color:#e7a84f;background:linear-gradient(135deg,#332215,#1a1512);box-shadow:0 0 0 1px #e7a84f22}.m7-convo-copy{min-width:0;flex:1}.m7-convo strong{color:#f1b45a}.m7-convo small{display:block;color:#aaa;margin-top:4px}.m7-new{background:#e58f25;color:#fff;font-size:9px;font-weight:900;border-radius:999px;padding:5px 7px}.m7-empty{text-align:center;color:#aaa;margin-top:30px}.m7-loading{text-align:center;color:#b7aa9d;margin-top:25px}.m7-error{text-align:center;color:#ffb3a8;margin:25px 12px;line-height:1.45}`;document.head.appendChild(s)}
function av(url,name){return url?`<img class="m7-avatar" src="${esc(url)}" alt="">`:`<div class="m7-avatar fallback">${esc((name||"?").slice(0,1).toUpperCase())}</div>`}
function shell(title,avatar,back){css();close(true);let x=document.createElement("div");x.id="m7-chat-shell";x.innerHTML=`<div id="m7-chat"><div id="m7-chat-head"><button class="m7c-icon" id="m7-back" style="display:${back?"block":"none"}">‹</button><div class="m7-head-person">${av(avatar,title)}<div id="m7-chat-title">${esc(title)}</div></div><button class="m7c-icon" id="m7-report" title="Report">⚑</button><button class="m7c-icon" id="m7-close">✕</button></div><div id="m7-chat-body"><div class="m7-loading">Loading…</div></div></div>`;document.body.appendChild(x);x.querySelector("#m7-close").onclick=()=>close();x.onclick=e=>{if(e.target===x)close()};return x}
function close(remove=true){if(channel&&client)try{client.removeChannel(channel)}catch(_){}channel=null;if(settingsChannel&&client)try{client.removeChannel(settingsChannel)}catch(_){}settingsChannel=null;if(remove)document.getElementById("m7-chat-shell")?.remove()}
const tm=v=>{try{return new Date(v).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}catch(_){return""}};
const sameId=(a,b)=>String(a??"")===String(b??"");
function loadError(b,e){if(!b)return;console.error("Ma7alak chat load error:",e);b.innerHTML=`<div class="m7-error">Could not load this conversation.<br><small>${esc(e?.message||"Please close Messages and try again.")}</small></div>`}
async function messages(c){let b=document.getElementById("m7-chat-body");if(!b)return false;if(!c||c.id==null){loadError(b,new Error("Conversation not found."));return false}try{let r=await Promise.race([client.from("ma7alak_messages").select("*").eq("conversation_id",c.id).order("created_at"),new Promise((_,reject)=>setTimeout(()=>reject(new Error("Message loading timed out. Please try again.")),12000))]);if(!b.isConnected)return false;if(r.error)throw r.error;b.innerHTML=(r.data||[]).map(m=>`<div class="m7-msg ${sameId(m.sender_id,user?.id)?"mine":""}">${esc(m.body)}<div class="m7-msg-time">${tm(m.created_at)}</div></div>`).join("")||'<div class="m7-empty">No messages yet.</div>';b.scrollTop=b.scrollHeight;client.rpc("ma7alak_mark_conversation_read",{p_conversation_id:c.id}).then(()=>dispatchEvent(new Event("ma7alak:messages-read"))).catch(e=>console.warn("Mark read failed:",e));return true}catch(e){loadError(b,e);return false}}
async function convo(c,title,avatar,back){shell(title,avatar,!!back);if(!c||c.id==null){loadError(document.getElementById("m7-chat-body"),new Error("Conversation not found."));return}if(back)document.getElementById("m7-back").onclick=back;document.getElementById("m7-report").onclick=async()=>{let reason=prompt("Why are you reporting this conversation?","Abusive messages");if(!reason)return;let r=await client.rpc("ma7alak_report_conversation",{p_conversation_id:c.id,p_reason:reason,p_details:"Reported from Ma7alak chat"});alert(r.error?r.error.message:"Report sent to Ma7alak Admin ✓")};document.getElementById("m7-chat").insertAdjacentHTML("beforeend",`<form id="m7-chat-send"><input id="m7-chat-input" maxlength="2000" placeholder="Type a message..." autocomplete="off"><button>Send</button></form>`);await messages(c);let form=document.getElementById("m7-chat-send");if(form)form.onsubmit=async e=>{e.preventDefault();let i=document.getElementById("m7-chat-input"),t=i?.value.trim();if(!t)return;i.value="";try{let r=await client.rpc("ma7alak_send_message",{p_conversation_id:c.id,p_body:t});if(r.error){alert(r.error.message);i.value=t}}catch(err){alert(err?.message||"Could not send message");i.value=t}};channel=client.channel("m7c-"+c.id+Math.random()).on("postgres_changes",{event:"INSERT",schema:"public",table:"ma7alak_messages",filter:"conversation_id=eq."+c.id},()=>messages(c)).subscribe()}
async function unreadMap(rows){let out=new Set;if(!rows.length)return out;try{let ids=rows.map(x=>x.id),r=await client.from("ma7alak_messages").select("conversation_id,sender_id,created_at").in("conversation_id",ids);if(r.error)return out;for(let m of r.data||[]){let c=rows.find(x=>sameId(x.id,m.conversation_id));if(!c)continue;let rd=mode==="owner"?c.owner_last_read_at:c.viewer_last_read_at;if(!sameId(m.sender_id,user?.id)&&(!rd||new Date(m.created_at)>new Date(rd)))out.add(String(m.conversation_id))}}catch(e){console.warn("Unread map failed:",e)}return out}
async function accepts(slug){let r=await client.rpc("ma7alak_shop_accepts_messages",{p_shop_slug:String(slug||"").trim()});if(r.error){console.warn("Message setting:",r.error);return true}return r.data!==false}
async function openShop(slug){try{await vr();if(!user){window.Ma7alakAccount?.open();return}slug=String(slug||"").trim();if(!await accepts(slug)){alert("Shop owner is currently not accepting messages");return}let r=await client.rpc("ma7alak_start_conversation",{p_shop_slug:slug});if(r.error){alert(r.error.message);return}let c=Array.isArray(r.data)?r.data[0]:r.data;if(!c){alert("Could not open conversation.");return}let sp=await client.from("shop_profiles").select("shop_name,profile_image_url").eq("shop_slug",c.shop_slug).maybeSingle();convo(c,sp.data?.shop_name||c.shop_slug,sp.data?.profile_image_url||"",null)}catch(e){console.error(e);alert(e?.message||"Could not open messages.")}}
async function viewerInbox(){try{await vr();if(!user){window.Ma7alakAccount?.open();return}shell("Messages","",false);document.getElementById("m7-report").style.display="none";let b=document.getElementById("m7-chat-body"),r=await client.from("ma7alak_conversations").select("*").order("updated_at",{ascending:false});if(r.error){b.textContent=r.error.message;return}let rows=r.data||[],slugs=[...new Set(rows.map(x=>x.shop_slug))];let [un,p]=await Promise.all([unreadMap(rows),slugs.length?client.from("shop_profiles").select("shop_slug,shop_name,profile_image_url").in("shop_slug",slugs):Promise.resolve({data:[]})]);let map={};for(let x of p.data||[])map[x.shop_slug]=x;b.innerHTML=rows.length?rows.map(c=>{let p=map[c.shop_slug]||{},n=p.shop_name||c.shop_slug,id=String(c.id);return `<div class="m7-convo ${un.has(id)?"unread":""}" data-id="${esc(id)}">${av(p.profile_image_url,n)}<div class="m7-convo-copy"><strong>${esc(n)}</strong><small>Shop conversation</small></div>${un.has(id)?'<span class="m7-new">NEW</span>':""}</div>`}).join(""):'<div class="m7-empty">No conversations yet.</div>';b.querySelectorAll(".m7-convo").forEach(el=>el.onclick=()=>{let c=rows.find(x=>sameId(x.id,el.dataset.id));if(!c){loadError(b,new Error("Conversation not found."));return}let p=map[c.shop_slug]||{};convo(c,p.shop_name||c.shop_slug,p.profile_image_url||"",viewerInbox)})}catch(e){loadError(document.getElementById("m7-chat-body"),e)}}
async function ownerInbox(){try{if(!await or()){window.Ma7alakOwnerAuth?.open();return}let shop=window.Ma7alakOwnerAuth.owner.shop_slug;shell("Shop Messages",window.Ma7alakOwnerAuth.owner.profile_image_url||"",false);document.getElementById("m7-report").style.display="none";let head=document.getElementById("m7-chat-head"),toggle=document.createElement("button");toggle.id="m7-owner-accept";head.insertBefore(toggle,document.getElementById("m7-close"));async function sync(){let on=await accepts(shop);toggle.className=on?"on":"off";toggle.textContent=on?"Messages ON":"Messages OFF";toggle.dataset.on=on?"1":"0"}toggle.onclick=async()=>{toggle.disabled=true;let next=toggle.dataset.on!=="1",r=await client.rpc("ma7alak_set_my_shop_accepting_messages",{p_shop_slug:shop,p_accepting:next});toggle.disabled=false;if(r.error){alert(r.error.message);return}sync()};await sync();settingsChannel=client.channel("m7-msg-setting-"+shop+Math.random()).on("postgres_changes",{event:"*",schema:"public",table:"ma7alak_shop_message_settings",filter:"shop_slug=eq."+shop},sync).subscribe();let b=document.getElementById("m7-chat-body"),r=await client.from("ma7alak_conversations").select("*").eq("shop_slug",shop).order("updated_at",{ascending:false});if(r.error){b.textContent=r.error.message;return}let rows=r.data||[],ids=[...new Set(rows.map(x=>x.viewer_id))];let [un,p]=await Promise.all([unreadMap(rows),ids.length?client.from("viewer_profiles").select("user_id,display_name,username,avatar_url").in("user_id",ids):Promise.resolve({data:[]})]);let map={};for(let x of p.data||[])map[x.user_id]=x;b.innerHTML=rows.length?rows.map(c=>{let p=map[c.viewer_id]||{},n=p.display_name||p.username||"Customer",id=String(c.id);return `<div class="m7-convo ${un.has(id)?"unread":""}" data-id="${esc(id)}">${av(p.avatar_url,n)}<div class="m7-convo-copy"><strong>${esc(n)}</strong><small>${esc(p.username?"@"+p.username:"Customer")}</small></div>${un.has(id)?'<span class="m7-new">NEW</span>':""}</div>`}).join(""):'<div class="m7-empty">No customer messages yet.</div>';b.querySelectorAll(".m7-convo").forEach(el=>el.onclick=()=>{let c=rows.find(x=>sameId(x.id,el.dataset.id));if(!c){loadError(b,new Error("Conversation not found."));return}let p=map[c.viewer_id]||{},n=p.display_name||p.username||"Customer";convo(c,n,p.avatar_url||"",ownerInbox)})}catch(e){loadError(document.getElementById("m7-chat-body"),e)}}
window.Ma7alakChat={openShop,openInbox:viewerInbox,openViewerInbox:viewerInbox,openOwnerInbox:ownerInbox,close};addEventListener("ma7alak:open-chat",e=>openShop(e.detail?.shop_slug));addEventListener("ma7alak:open-messages",viewerInbox);addEventListener("ma7alak:open-owner-messages",ownerInbox);
})();
