/* =========================================================
   MA7ALAK LIVE CHAT UI V2
   - Viewer opens shop chat in bottom sheet
   - Viewer inbox uses isolated Viewer client
   - Owner inbox uses separate Owner client
   - Owner sees customer names and can reply live
========================================================= */
(function(){
"use strict";
if(window.__MA7ALAK_CHAT_V2__)return;window.__MA7ALAK_CHAT_V2__=true;
let client=null,user=null,mode="viewer",activeConversation=null,channel=null;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const esc=v=>String(v||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
async function viewerReady(){for(let i=0;i<100&&!window.Ma7alakAccount;i++)await sleep(50);if(!window.Ma7alakAccount)throw new Error("viewer-account.js is not loaded");await window.Ma7alakAccount.ready();client=window.Ma7alakAccount.client;user=window.Ma7alakAccount.user;mode="viewer";}
async function ownerReady(){for(let i=0;i<100&&!window.Ma7alakOwnerAuth;i++)await sleep(50);if(!window.Ma7alakOwnerAuth)throw new Error("owner auth is not loaded");await window.Ma7alakOwnerAuth.ready();client=window.Ma7alakOwnerAuth.client;user=window.Ma7alakOwnerAuth.user;mode="owner";return !!(user&&window.Ma7alakOwnerAuth.owner?.shop_slug);}
function styles(){if(document.getElementById("m7-chat-css"))return;const s=document.createElement("style");s.id="m7-chat-css";s.textContent=`#m7-chat-shell{position:fixed;inset:0;background:rgba(0,0,0,.72);z-index:2147483500;display:flex;align-items:flex-end;justify-content:center;font-family:Arial,sans-serif}#m7-chat{width:min(520px,100%);height:min(760px,92vh);background:#100e0d;color:#fff;border:1px solid rgba(219,155,70,.35);border-radius:24px 24px 0 0;display:flex;flex-direction:column;overflow:hidden}#m7-chat-head{padding:14px 16px;background:#1d1511;border-bottom:1px solid #3b2a20;display:flex;align-items:center;gap:10px}#m7-chat-title{font-weight:900;flex:1;color:#f1b45a}.m7c-icon{border:0;background:#30251f;color:#fff;border-radius:10px;padding:8px 11px;cursor:pointer}#m7-chat-body{flex:1;overflow:auto;padding:14px;display:flex;flex-direction:column;gap:9px}.m7-msg{max-width:78%;padding:10px 12px;border-radius:16px;background:#29231f;line-height:1.35;word-break:break-word}.m7-msg.mine{align-self:flex-end;background:#a96d28;color:#fff}.m7-msg-time{font-size:10px;opacity:.65;margin-top:4px}#m7-chat-send{display:flex;gap:8px;padding:10px;background:#171310;border-top:1px solid #34261e}#m7-chat-input{flex:1;border:1px solid #453327;background:#0e0c0b;color:#fff;border-radius:14px;padding:12px;outline:none}#m7-chat-send button{border:0;border-radius:14px;background:#d99a45;font-weight:900;padding:0 17px;cursor:pointer}.m7-convo{padding:13px;border:1px solid #34281f;border-radius:15px;background:#191512;cursor:pointer}.m7-convo strong{color:#f1b45a}.m7-convo small{display:block;color:#aaa;margin-top:4px}.m7-empty{color:#aaa;text-align:center;margin-top:30px}`;document.head.appendChild(s);}
function shell(title,back){styles();document.getElementById("m7-chat-shell")?.remove();const x=document.createElement("div");x.id="m7-chat-shell";x.innerHTML=`<div id="m7-chat"><div id="m7-chat-head"><button class="m7c-icon" id="m7-chat-back" style="display:${back?"block":"none"}">‹</button><div id="m7-chat-title">${esc(title)}</div><button class="m7c-icon" id="m7-chat-close">✕</button></div><div id="m7-chat-body"></div></div>`;document.body.appendChild(x);document.getElementById("m7-chat-close").onclick=close;x.onclick=e=>{if(e.target===x)close();};return x;}
function close(){if(channel&&client)try{client.removeChannel(channel);}catch(_){}channel=null;activeConversation=null;document.getElementById("m7-chat-shell")?.remove();}
function time(v){try{return new Date(v).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"});}catch(_){return "";}}
async function loadMessages(id){const body=document.getElementById("m7-chat-body");if(!body)return;const r=await client.from("ma7alak_messages").select("*").eq("conversation_id",id).order("created_at",{ascending:true});if(r.error){body.innerHTML=`<div>${esc(r.error.message)}</div>`;return;}body.innerHTML=(r.data||[]).map(m=>`<div class="m7-msg ${m.sender_id===user.id?"mine":""}">${esc(m.body)}<div class="m7-msg-time">${time(m.created_at)}</div></div>`).join("");body.scrollTop=body.scrollHeight;await client.rpc("ma7alak_mark_conversation_read",{p_conversation_id:id});window.dispatchEvent(new CustomEvent("ma7alak:messages-read"));}
async function showConversation(c,title,backFn){activeConversation=c;shell(title||c.shop_slug,!!backFn);if(backFn)document.getElementById("m7-chat-back").onclick=backFn;const chat=document.getElementById("m7-chat");chat.insertAdjacentHTML("beforeend",`<form id="m7-chat-send"><input id="m7-chat-input" maxlength="2000" autocomplete="off" placeholder="Type a message..."><button>Send</button></form>`);await loadMessages(c.id);document.getElementById("m7-chat-send").onsubmit=async e=>{e.preventDefault();const input=document.getElementById("m7-chat-input"),text=input.value.trim();if(!text)return;input.value="";const r=await client.rpc("ma7alak_send_message",{p_conversation_id:c.id,p_body:text});if(r.error){alert(r.error.message);input.value=text;}};if(channel)try{client.removeChannel(channel);}catch(_){}channel=client.channel("m7-chat-"+c.id+"-"+Math.random().toString(36).slice(2)).on("postgres_changes",{event:"INSERT",schema:"public",table:"ma7alak_messages",filter:"conversation_id=eq."+c.id},()=>loadMessages(c.id)).subscribe();}
async function openShop(slug){await viewerReady();user=window.Ma7alakAccount.user;if(!user){window.Ma7alakAccount.open();return;}const s=String(slug||"").trim();if(!s){alert("This shop is missing its Ma7alak shop ID.");return;}const r=await client.rpc("ma7alak_start_conversation",{p_shop_slug:s});if(r.error){alert(r.error.message);return;}const c=Array.isArray(r.data)?r.data[0]:r.data;let name=s;const sp=await client.from("shop_profiles").select("shop_name").eq("shop_slug",s).maybeSingle();if(sp.data?.shop_name)name=sp.data.shop_name;await showConversation(c,name,null);}
async function viewerInbox(){await viewerReady();user=window.Ma7alakAccount.user;if(!user){window.Ma7alakAccount.open();return;}shell("Messages",false);const body=document.getElementById("m7-chat-body");body.innerHTML="Loading...";const r=await client.from("ma7alak_conversations").select("*").order("updated_at",{ascending:false});if(r.error){body.innerHTML=esc(r.error.message);return;}const rows=r.data||[];if(!rows.length){body.innerHTML='<div class="m7-empty">No conversations yet.</div>';return;}body.innerHTML=rows.map(c=>`<div class="m7-convo" data-id="${c.id}"><strong>${esc(c.shop_slug)}</strong><small>Shop conversation</small></div>`).join("");body.querySelectorAll(".m7-convo").forEach(el=>el.onclick=()=>{const c=rows.find(x=>x.id===el.dataset.id);showConversation(c,c.shop_slug,viewerInbox);});}
async function ownerInbox(){if(!await ownerReady()){alert("Shop Owner Login required.");window.Ma7alakOwnerAuth?.open();return;}const shop=window.Ma7alakOwnerAuth.owner.shop_slug;shell("Shop Messages",false);const body=document.getElementById("m7-chat-body");body.innerHTML="Loading...";const r=await client.from("ma7alak_conversations").select("*").eq("shop_slug",shop).order("updated_at",{ascending:false});if(r.error){body.innerHTML=esc(r.error.message);return;}const rows=r.data||[];if(!rows.length){body.innerHTML='<div class="m7-empty">No customer messages yet.</div>';return;}const ids=[...new Set(rows.map(x=>x.viewer_id))],profiles={};if(ids.length){const p=await client.from("viewer_profiles").select("user_id,display_name,username").in("user_id",ids);(p.data||[]).forEach(x=>profiles[x.user_id]=x);}body.innerHTML=rows.map(c=>{const p=profiles[c.viewer_id],label=p?.display_name||p?.username||"Customer";return `<div class="m7-convo" data-id="${c.id}"><strong>${esc(label)}</strong><small>Customer · ${esc(shop)}</small></div>`;}).join("");body.querySelectorAll(".m7-convo").forEach(el=>el.onclick=()=>{const c=rows.find(x=>x.id===el.dataset.id),p=profiles[c.viewer_id];showConversation(c,p?.display_name||p?.username||"Customer",ownerInbox);});}
window.Ma7alakChat={openShop,openInbox:viewerInbox,openViewerInbox:viewerInbox,openOwnerInbox:ownerInbox,close};window.addEventListener("ma7alak:open-chat",e=>openShop(e.detail?.shop_slug));window.addEventListener("ma7alak:open-messages",()=>viewerInbox());window.addEventListener("ma7alak:open-owner-messages",()=>ownerInbox());
})();