-- =========================================================
-- SHOUFHON — OPTIONAL SHOP CATALOG / MENU & PRICES V1
-- Admin controls entitlement in shop_profiles.directory_options.
-- Owners edit content only through authenticated RPCs.
-- Public viewers receive only active/visible catalog content.
-- =========================================================

create table if not exists public.shop_catalogs (
  shop_slug text primary key
    references public.shop_profiles(shop_slug)
    on update cascade
    on delete cascade,
  title text not null default 'Menu & Prices'
    check (char_length(title) between 1 and 80),
  subtitle text null
    check (subtitle is null or char_length(subtitle) <= 180),
  default_currency text not null default 'USD'
    check (default_currency ~ '^[A-Z]{2,6}$'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.shop_catalog_sections (
  id bigint generated by default as identity primary key,
  shop_slug text not null
    references public.shop_catalogs(shop_slug)
    on update cascade
    on delete cascade,
  title text not null
    check (char_length(title) between 1 and 80),
  description text null
    check (description is null or char_length(description) <= 240),
  sort_order integer not null default 0,
  is_visible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(id, shop_slug)
);

create table if not exists public.shop_catalog_items (
  id bigint generated by default as identity primary key,
  shop_slug text not null,
  section_id bigint not null,
  name text not null
    check (char_length(name) between 1 and 120),
  description text null
    check (description is null or char_length(description) <= 600),
  badge text null
    check (badge is null or char_length(badge) <= 24),
  image_url text null
    check (image_url is null or char_length(image_url) <= 1400),
  image_storage_path text null
    check (image_storage_path is null or char_length(image_storage_path) <= 500),
  price_mode text not null default 'fixed'
    check (price_mode in ('fixed','from','multiple','contact','free')),
  base_price numeric(14,2) null
    check (base_price is null or (base_price >= 0 and base_price <= 999999999999.99)),
  currency text not null default 'USD'
    check (currency ~ '^[A-Z]{2,6}$'),
  price_label text null
    check (price_label is null or char_length(price_label) <= 80),
  is_available boolean not null default true,
  is_visible boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint shop_catalog_items_section_fk
    foreign key (section_id, shop_slug)
    references public.shop_catalog_sections(id, shop_slug)
    on update cascade
    on delete cascade,
  unique(id, shop_slug)
);

create table if not exists public.shop_catalog_item_prices (
  id bigint generated by default as identity primary key,
  item_id bigint not null
    references public.shop_catalog_items(id)
    on update cascade
    on delete cascade,
  label text not null
    check (char_length(label) between 1 and 60),
  amount numeric(14,2) null
    check (amount is null or (amount >= 0 and amount <= 999999999999.99)),
  price_text text null
    check (price_text is null or char_length(price_text) <= 80),
  currency text not null default 'USD'
    check (currency ~ '^[A-Z]{2,6}$'),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  check (amount is not null or nullif(trim(price_text),'') is not null)
);

create index if not exists shop_catalog_sections_shop_order_idx
  on public.shop_catalog_sections(shop_slug, sort_order, id);

create index if not exists shop_catalog_items_shop_section_order_idx
  on public.shop_catalog_items(shop_slug, section_id, sort_order, id);

create index if not exists shop_catalog_item_prices_item_order_idx
  on public.shop_catalog_item_prices(item_id, sort_order, id);

alter table public.shop_catalogs enable row level security;
alter table public.shop_catalog_sections enable row level security;
alter table public.shop_catalog_items enable row level security;
alter table public.shop_catalog_item_prices enable row level security;

revoke all on table public.shop_catalogs from anon, authenticated;
revoke all on table public.shop_catalog_sections from anon, authenticated;
revoke all on table public.shop_catalog_items from anon, authenticated;
revoke all on table public.shop_catalog_item_prices from anon, authenticated;

grant select on table public.shop_catalogs to anon, authenticated;

drop policy if exists "Public can read enabled catalog header"
  on public.shop_catalogs;

create policy "Public can read enabled catalog header"
on public.shop_catalogs
for select
to anon, authenticated
using (
  exists (
    select 1
    from public.shop_profiles p
    where p.shop_slug = shop_catalogs.shop_slug
      and p.is_active is true
      and coalesce(
        lower(p.directory_options ->> 'catalog_enabled')
          in ('true','1','yes','on'),
        false
      )
  )
);

-- -----------------------------------------------------------------
-- One internal snapshot builder. This is never exposed to API roles.
-- -----------------------------------------------------------------
create or replace function private.ma7alak_catalog_snapshot(
  p_shop_slug text,
  p_include_hidden boolean default false
)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'shop_slug', p.shop_slug,
    'shop_name', p.shop_name,
    'enabled',
      (
        p.is_active is true
        and coalesce(
          lower(p.directory_options ->> 'catalog_enabled')
            in ('true','1','yes','on'),
          false
        )
      ),
    'options',
      jsonb_build_object(
        'catalog_images_enabled', coalesce(p.directory_options -> 'catalog_images_enabled','true'::jsonb),
        'catalog_max_sections', coalesce(p.directory_options -> 'catalog_max_sections','10'::jsonb),
        'catalog_max_items', coalesce(p.directory_options -> 'catalog_max_items','60'::jsonb),
        'catalog_max_prices', coalesce(p.directory_options -> 'catalog_max_prices','6'::jsonb),
        'gallery_accent_color', p.directory_options -> 'gallery_accent_color',
        'story_color', p.directory_options -> 'story_color',
        'card_color', p.directory_options -> 'card_color',
        'media_title_color', p.directory_options -> 'media_title_color',
        'media_count_color', p.directory_options -> 'media_count_color',
        'media_header_bg_color', p.directory_options -> 'media_header_bg_color',
        'media_header_frame_color', p.directory_options -> 'media_header_frame_color',
        'media_symbol_color', p.directory_options -> 'media_symbol_color',
        'media_symbol_frame_color', p.directory_options -> 'media_symbol_frame_color',
        'media_symbol_bg_color', p.directory_options -> 'media_symbol_bg_color',
        'media_button_text_color', p.directory_options -> 'media_button_text_color',
        'media_button_frame_color', p.directory_options -> 'media_button_frame_color',
        'media_button_bg_color', p.directory_options -> 'media_button_bg_color',
        'media_button_active_text_color', p.directory_options -> 'media_button_active_text_color',
        'media_button_active_frame_color', p.directory_options -> 'media_button_active_frame_color',
        'media_button_active_bg_color', p.directory_options -> 'media_button_active_bg_color',
        'profile_shell_bg_color', p.directory_options -> 'profile_shell_bg_color',
        'profile_shell_border_color', p.directory_options -> 'profile_shell_border_color',
        'profile_shell_radius', p.directory_options -> 'profile_shell_radius'
      ),
    'catalog',
      jsonb_build_object(
        'title', coalesce(c.title, 'Menu & Prices'),
        'subtitle', coalesce(c.subtitle, ''),
        'default_currency', coalesce(c.default_currency, 'USD'),
        'updated_at', c.updated_at
      ),
    'sections',
      coalesce(
        (
          select jsonb_agg(
            jsonb_build_object(
              'id', s.id,
              'title', s.title,
              'description', coalesce(s.description,''),
              'sort_order', s.sort_order,
              'is_visible', s.is_visible,
              'items',
                coalesce(
                  (
                    select jsonb_agg(
                      jsonb_build_object(
                        'id', i.id,
                        'section_id', i.section_id,
                        'name', i.name,
                        'description', coalesce(i.description,''),
                        'badge', coalesce(i.badge,''),
                        'image_url', coalesce(i.image_url,''),
                        'image_storage_path', coalesce(i.image_storage_path,''),
                        'price_mode', i.price_mode,
                        'base_price', i.base_price,
                        'currency', i.currency,
                        'price_label', coalesce(i.price_label,''),
                        'is_available', i.is_available,
                        'is_visible', i.is_visible,
                        'sort_order', i.sort_order,
                        'prices',
                          coalesce(
                            (
                              select jsonb_agg(
                                jsonb_build_object(
                                  'id', pr.id,
                                  'label', pr.label,
                                  'amount', pr.amount,
                                  'price_text', coalesce(pr.price_text,''),
                                  'currency', pr.currency,
                                  'sort_order', pr.sort_order
                                )
                                order by pr.sort_order, pr.id
                              )
                              from public.shop_catalog_item_prices pr
                              where pr.item_id = i.id
                            ),
                            '[]'::jsonb
                          )
                      )
                      order by i.sort_order, i.id
                    )
                    from public.shop_catalog_items i
                    where i.shop_slug = p.shop_slug
                      and i.section_id = s.id
                      and (p_include_hidden or i.is_visible is true)
                  ),
                  '[]'::jsonb
                )
            )
            order by s.sort_order, s.id
          )
          from public.shop_catalog_sections s
          where s.shop_slug = p.shop_slug
            and (p_include_hidden or s.is_visible is true)
        ),
        '[]'::jsonb
      )
  )
  from public.shop_profiles p
  left join public.shop_catalogs c
    on c.shop_slug = p.shop_slug
  where p.shop_slug = lower(trim(coalesce(p_shop_slug,'')))
  limit 1;
$$;

revoke all on function private.ma7alak_catalog_snapshot(text,boolean)
  from public, anon, authenticated;

-- -----------------------------------------------------------------
-- Public read RPC.
-- -----------------------------------------------------------------
create or replace function public.ma7alak_get_shop_catalog(
  p_shop_slug text
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_slug text := lower(trim(coalesce(p_shop_slug,'')));
  v_active boolean := false;
  v_enabled boolean := false;
begin
  if v_slug = '' then
    return jsonb_build_object('enabled',false,'sections','[]'::jsonb);
  end if;

  select
    p.is_active is true,
    coalesce(
      lower(p.directory_options ->> 'catalog_enabled')
        in ('true','1','yes','on'),
      false
    )
  into v_active, v_enabled
  from public.shop_profiles p
  where p.shop_slug = v_slug;

  if not found or not v_active or not v_enabled then
    return jsonb_build_object(
      'shop_slug',v_slug,
      'enabled',false,
      'sections','[]'::jsonb
    );
  end if;

  return private.ma7alak_catalog_snapshot(v_slug,false);
end;
$$;

revoke all on function public.ma7alak_get_shop_catalog(text)
  from public, anon, authenticated;
grant execute on function public.ma7alak_get_shop_catalog(text)
  to anon, authenticated;

-- -----------------------------------------------------------------
-- Owner read RPC. Catalog must be enabled by Admin.
-- -----------------------------------------------------------------
create or replace function public.ma7alak_owner_get_catalog(
  p_shop_slug text
)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_slug text := lower(trim(coalesce(p_shop_slug,'')));
begin
  if (select auth.uid()) is null then
    raise exception 'Owner login required.';
  end if;

  if not exists (
    select 1
    from public.shop_owners o
    where o.user_id = (select auth.uid())
      and o.shop_slug = v_slug
  ) then
    raise exception 'This account does not own this shop.';
  end if;

  if not public.owner_has_shop_option(v_slug,'catalog_enabled') then
    raise exception 'Catalog is disabled by Admin.';
  end if;

  insert into public.shop_catalogs(shop_slug)
  values(v_slug)
  on conflict(shop_slug) do nothing;

  return private.ma7alak_catalog_snapshot(v_slug,true);
end;
$$;

revoke all on function public.ma7alak_owner_get_catalog(text)
  from public, anon, authenticated;
grant execute on function public.ma7alak_owner_get_catalog(text)
  to authenticated;

-- -----------------------------------------------------------------
-- Owner mutation RPC. All writes are ownership checked server-side.
-- -----------------------------------------------------------------
create or replace function public.ma7alak_owner_catalog_mutate(
  p_shop_slug text,
  p_action text,
  p_payload jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_slug text := lower(trim(coalesce(p_shop_slug,'')));
  v_action text := lower(trim(coalesce(p_action,'')));
  v_payload jsonb := coalesce(p_payload,'{}'::jsonb);
  v_options jsonb := '{}'::jsonb;
  v_max_sections integer := 10;
  v_max_items integer := 60;
  v_max_prices integer := 6;
  v_images_enabled boolean := true;
  v_id bigint;
  v_section_id bigint;
  v_item_id bigint;
  v_title text;
  v_description text;
  v_name text;
  v_badge text;
  v_mode text;
  v_currency text;
  v_price_label text;
  v_image_mode text;
  v_image_url text;
  v_image_path text;
  v_old_image_path text;
  v_base_text text;
  v_base numeric(14,2);
  v_is_visible boolean;
  v_is_available boolean;
  v_cleanup text[] := '{}'::text[];
  v_row jsonb;
  v_price jsonb;
  v_price_count integer := 0;
  v_amount_text text;
  v_amount numeric(14,2);
  v_price_text text;
  v_price_currency text;
  v_sort integer;
begin
  if (select auth.uid()) is null then
    raise exception 'Owner login required.';
  end if;

  if not exists (
    select 1
    from public.shop_owners o
    where o.user_id = (select auth.uid())
      and o.shop_slug = v_slug
  ) then
    raise exception 'This account does not own this shop.';
  end if;

  select p.directory_options
  into v_options
  from public.shop_profiles p
  where p.shop_slug = v_slug;

  if not found then
    raise exception 'Shop profile was not found.';
  end if;

  if not coalesce(
    lower(v_options ->> 'catalog_enabled') in ('true','1','yes','on'),
    false
  ) then
    raise exception 'Catalog is disabled by Admin.';
  end if;

  if coalesce(v_options ->> 'catalog_max_sections','') ~ '^[0-9]+$' then
    v_max_sections := greatest(1,least(30,(v_options ->> 'catalog_max_sections')::integer));
  end if;

  if coalesce(v_options ->> 'catalog_max_items','') ~ '^[0-9]+$' then
    v_max_items := greatest(1,least(300,(v_options ->> 'catalog_max_items')::integer));
  end if;

  if coalesce(v_options ->> 'catalog_max_prices','') ~ '^[0-9]+$' then
    v_max_prices := greatest(1,least(20,(v_options ->> 'catalog_max_prices')::integer));
  end if;

  if v_options ? 'catalog_images_enabled' then
    v_images_enabled :=
      coalesce(
        lower(v_options ->> 'catalog_images_enabled')
          in ('true','1','yes','on'),
        false
      );
  end if;

  insert into public.shop_catalogs(shop_slug)
  values(v_slug)
  on conflict(shop_slug) do nothing;

  if v_action = 'settings-save' then
    v_title := trim(coalesce(v_payload ->> 'title',''));
    v_description := nullif(trim(coalesce(v_payload ->> 'subtitle','')),'');
    v_currency := upper(trim(coalesce(v_payload ->> 'default_currency','USD')));

    if char_length(v_title) < 1 or char_length(v_title) > 80 then
      raise exception 'Catalog title must be 1 to 80 characters.';
    end if;

    if v_description is not null and char_length(v_description) > 180 then
      raise exception 'Catalog subtitle is too long.';
    end if;

    if v_currency !~ '^[A-Z]{2,6}$' then
      raise exception 'Choose a valid currency code.';
    end if;

    update public.shop_catalogs
    set title=v_title,
        subtitle=v_description,
        default_currency=v_currency,
        updated_at=now()
    where shop_slug=v_slug;

  elsif v_action = 'section-save' then
    v_title := trim(coalesce(v_payload ->> 'title',''));
    v_description := nullif(trim(coalesce(v_payload ->> 'description','')),'');
    v_is_visible := coalesce((v_payload ->> 'is_visible')::boolean,true);

    if char_length(v_title) < 1 or char_length(v_title) > 80 then
      raise exception 'Section title must be 1 to 80 characters.';
    end if;

    if v_description is not null and char_length(v_description) > 240 then
      raise exception 'Section description is too long.';
    end if;

    if coalesce(v_payload ->> 'id','') ~ '^[0-9]+$' then
      v_id := (v_payload ->> 'id')::bigint;
    else
      v_id := null;
    end if;

    if v_id is null then
      if (
        select count(*)
        from public.shop_catalog_sections s
        where s.shop_slug=v_slug
      ) >= v_max_sections then
        raise exception 'Admin limit: maximum % sections.',v_max_sections;
      end if;

      select coalesce(max(s.sort_order),-1)+1
      into v_sort
      from public.shop_catalog_sections s
      where s.shop_slug=v_slug;

      insert into public.shop_catalog_sections(
        shop_slug,title,description,sort_order,is_visible
      )
      values(
        v_slug,v_title,v_description,v_sort,v_is_visible
      );
    else
      update public.shop_catalog_sections
      set title=v_title,
          description=v_description,
          is_visible=v_is_visible,
          updated_at=now()
      where id=v_id
        and shop_slug=v_slug;

      if not found then
        raise exception 'Section was not found.';
      end if;
    end if;

  elsif v_action = 'section-delete' then
    if coalesce(v_payload ->> 'id','') !~ '^[0-9]+$' then
      raise exception 'Section was not found.';
    end if;

    v_id := (v_payload ->> 'id')::bigint;

    select coalesce(
      array_agg(i.image_storage_path)
        filter (where nullif(i.image_storage_path,'') is not null),
      '{}'::text[]
    )
    into v_cleanup
    from public.shop_catalog_items i
    where i.shop_slug=v_slug
      and i.section_id=v_id;

    delete from public.shop_catalog_sections
    where id=v_id
      and shop_slug=v_slug;

    if not found then
      raise exception 'Section was not found.';
    end if;

  elsif v_action = 'section-reorder' then
    if jsonb_typeof(v_payload -> 'ids') <> 'array' then
      raise exception 'Section order is invalid.';
    end if;

    v_sort := 0;

    for v_row in
      select value
      from jsonb_array_elements(v_payload -> 'ids')
    loop
      if trim(both '"' from v_row::text) ~ '^[0-9]+$' then
        v_id := trim(both '"' from v_row::text)::bigint;
        update public.shop_catalog_sections
        set sort_order=v_sort,
            updated_at=now()
        where id=v_id
          and shop_slug=v_slug;
        v_sort := v_sort + 1;
      end if;
    end loop;

  elsif v_action = 'item-save' then
    if coalesce(v_payload ->> 'section_id','') !~ '^[0-9]+$' then
      raise exception 'Choose a valid section.';
    end if;

    v_section_id := (v_payload ->> 'section_id')::bigint;

    if not exists (
      select 1
      from public.shop_catalog_sections s
      where s.id=v_section_id
        and s.shop_slug=v_slug
    ) then
      raise exception 'Section was not found.';
    end if;

    v_name := trim(coalesce(v_payload ->> 'name',''));
    v_description := nullif(trim(coalesce(v_payload ->> 'description','')),'');
    v_badge := nullif(trim(coalesce(v_payload ->> 'badge','')),'');
    v_mode := lower(trim(coalesce(v_payload ->> 'price_mode','fixed')));
    v_currency := upper(trim(coalesce(v_payload ->> 'currency','USD')));
    v_price_label := nullif(trim(coalesce(v_payload ->> 'price_label','')),'');
    v_image_mode := lower(trim(coalesce(v_payload ->> 'image_mode','keep')));
    v_is_available := coalesce((v_payload ->> 'is_available')::boolean,true);
    v_is_visible := coalesce((v_payload ->> 'is_visible')::boolean,true);

    if char_length(v_name) < 1 or char_length(v_name) > 120 then
      raise exception 'Item name must be 1 to 120 characters.';
    end if;

    if v_description is not null and char_length(v_description) > 600 then
      raise exception 'Item description is too long.';
    end if;

    if v_badge is not null and char_length(v_badge) > 24 then
      raise exception 'Item badge is too long.';
    end if;

    if v_mode not in ('fixed','from','multiple','contact','free') then
      raise exception 'Choose a valid price type.';
    end if;

    if v_currency !~ '^[A-Z]{2,6}$' then
      raise exception 'Choose a valid currency code.';
    end if;

    if v_price_label is not null and char_length(v_price_label) > 80 then
      raise exception 'Price label is too long.';
    end if;

    v_base_text := trim(coalesce(v_payload ->> 'base_price',''));
    v_base := null;
    if v_base_text <> '' then
      if v_base_text !~ '^[0-9]+([.][0-9]{1,2})?$' then
        raise exception 'Enter a valid price.';
      end if;
      v_base := v_base_text::numeric(14,2);
    end if;

    if v_mode in ('fixed','from') and v_base is null then
      raise exception 'Enter a price.';
    end if;

    if v_mode in ('contact','free') then
      v_base := null;
    end if;

    if coalesce(v_payload ->> 'id','') ~ '^[0-9]+$' then
      v_item_id := (v_payload ->> 'id')::bigint;
    else
      v_item_id := null;
    end if;

    if v_item_id is null then
      if (
        select count(*)
        from public.shop_catalog_items i
        where i.shop_slug=v_slug
      ) >= v_max_items then
        raise exception 'Admin limit: maximum % catalog items.',v_max_items;
      end if;
    else
      select i.image_storage_path
      into v_old_image_path
      from public.shop_catalog_items i
      where i.id=v_item_id
        and i.shop_slug=v_slug;

      if not found then
        raise exception 'Catalog item was not found.';
      end if;
    end if;

    if v_image_mode = 'replace' then
      if not v_images_enabled then
        raise exception 'Catalog images are disabled by Admin.';
      end if;

      v_image_url := nullif(trim(coalesce(v_payload ->> 'image_url','')),'');
      v_image_path := nullif(trim(coalesce(v_payload ->> 'image_storage_path','')),'');

      if v_image_url is null or v_image_path is null then
        raise exception 'The uploaded catalog image is missing.';
      end if;

      if v_image_path not like ('owner-catalog/' || v_slug || '/%') then
        raise exception 'Catalog image path is invalid.';
      end if;

      if position('/shop-gallery/owner-catalog/' || v_slug || '/' in v_image_url) = 0 then
        raise exception 'Catalog image URL is invalid.';
      end if;

    elsif v_image_mode = 'remove' then
      v_image_url := null;
      v_image_path := null;

    elsif v_image_mode = 'keep' and v_item_id is not null then
      select i.image_url,i.image_storage_path
      into v_image_url,v_image_path
      from public.shop_catalog_items i
      where i.id=v_item_id
        and i.shop_slug=v_slug;

    else
      v_image_url := null;
      v_image_path := null;
    end if;

    if v_item_id is null then
      select coalesce(max(i.sort_order),-1)+1
      into v_sort
      from public.shop_catalog_items i
      where i.shop_slug=v_slug
        and i.section_id=v_section_id;

      insert into public.shop_catalog_items(
        shop_slug,section_id,name,description,badge,
        image_url,image_storage_path,price_mode,base_price,
        currency,price_label,is_available,is_visible,sort_order
      )
      values(
        v_slug,v_section_id,v_name,v_description,v_badge,
        v_image_url,v_image_path,v_mode,v_base,
        v_currency,v_price_label,v_is_available,v_is_visible,v_sort
      )
      returning id into v_item_id;
    else
      update public.shop_catalog_items
      set section_id=v_section_id,
          name=v_name,
          description=v_description,
          badge=v_badge,
          image_url=v_image_url,
          image_storage_path=v_image_path,
          price_mode=v_mode,
          base_price=v_base,
          currency=v_currency,
          price_label=v_price_label,
          is_available=v_is_available,
          is_visible=v_is_visible,
          updated_at=now()
      where id=v_item_id
        and shop_slug=v_slug;

      if v_old_image_path is not null
         and v_old_image_path <> ''
         and coalesce(v_old_image_path,'') <> coalesce(v_image_path,'') then
        v_cleanup := array_append(v_cleanup,v_old_image_path);
      end if;
    end if;

    delete from public.shop_catalog_item_prices
    where item_id=v_item_id;

    if jsonb_typeof(coalesce(v_payload -> 'prices','[]'::jsonb)) <> 'array' then
      raise exception 'Price options are invalid.';
    end if;

    v_price_count := jsonb_array_length(coalesce(v_payload -> 'prices','[]'::jsonb));

    if v_price_count > v_max_prices then
      raise exception 'Admin limit: maximum % price options per item.',v_max_prices;
    end if;

    if v_mode='multiple' and v_price_count < 1 then
      raise exception 'Add at least one price option.';
    end if;

    v_sort := 0;

    for v_price in
      select value
      from jsonb_array_elements(coalesce(v_payload -> 'prices','[]'::jsonb))
    loop
      v_title := trim(coalesce(v_price ->> 'label',''));
      v_amount_text := trim(coalesce(v_price ->> 'amount',''));
      v_price_text := nullif(trim(coalesce(v_price ->> 'price_text','')),'');
      v_price_currency := upper(trim(coalesce(v_price ->> 'currency',v_currency)));

      if char_length(v_title) < 1 or char_length(v_title) > 60 then
        raise exception 'Each price option needs a label.';
      end if;

      if v_price_currency !~ '^[A-Z]{2,6}$' then
        raise exception 'One price option has an invalid currency.';
      end if;

      v_amount := null;
      if v_amount_text <> '' then
        if v_amount_text !~ '^[0-9]+([.][0-9]{1,2})?$' then
          raise exception 'One price option has an invalid amount.';
        end if;
        v_amount := v_amount_text::numeric(14,2);
      end if;

      if v_amount is null and v_price_text is null then
        raise exception 'Each price option needs an amount or text.';
      end if;

      if v_price_text is not null and char_length(v_price_text) > 80 then
        raise exception 'One price option text is too long.';
      end if;

      insert into public.shop_catalog_item_prices(
        item_id,label,amount,price_text,currency,sort_order
      )
      values(
        v_item_id,v_title,v_amount,v_price_text,v_price_currency,v_sort
      );

      v_sort := v_sort + 1;
    end loop;

  elsif v_action = 'item-delete' then
    if coalesce(v_payload ->> 'id','') !~ '^[0-9]+$' then
      raise exception 'Catalog item was not found.';
    end if;

    v_item_id := (v_payload ->> 'id')::bigint;

    select i.image_storage_path
    into v_old_image_path
    from public.shop_catalog_items i
    where i.id=v_item_id
      and i.shop_slug=v_slug;

    if not found then
      raise exception 'Catalog item was not found.';
    end if;

    if nullif(v_old_image_path,'') is not null then
      v_cleanup := array_append(v_cleanup,v_old_image_path);
    end if;

    delete from public.shop_catalog_items
    where id=v_item_id
      and shop_slug=v_slug;

  elsif v_action = 'item-reorder' then
    if coalesce(v_payload ->> 'section_id','') !~ '^[0-9]+$' then
      raise exception 'Section was not found.';
    end if;

    v_section_id := (v_payload ->> 'section_id')::bigint;

    if jsonb_typeof(v_payload -> 'ids') <> 'array' then
      raise exception 'Item order is invalid.';
    end if;

    v_sort := 0;
    for v_row in
      select value
      from jsonb_array_elements(v_payload -> 'ids')
    loop
      if trim(both '"' from v_row::text) ~ '^[0-9]+$' then
        v_item_id := trim(both '"' from v_row::text)::bigint;
        update public.shop_catalog_items
        set sort_order=v_sort,
            updated_at=now()
        where id=v_item_id
          and shop_slug=v_slug
          and section_id=v_section_id;
        v_sort := v_sort + 1;
      end if;
    end loop;

  else
    raise exception 'Unknown Catalog action.';
  end if;

  update public.shop_catalogs
  set updated_at=now()
  where shop_slug=v_slug;

  return jsonb_build_object(
    'snapshot', private.ma7alak_catalog_snapshot(v_slug,true),
    'cleanup_paths', to_jsonb(v_cleanup)
  );
end;
$$;

revoke all on function public.ma7alak_owner_catalog_mutate(text,text,jsonb)
  from public, anon, authenticated;
grant execute on function public.ma7alak_owner_catalog_mutate(text,text,jsonb)
  to authenticated;

-- -----------------------------------------------------------------
-- Catalog image Storage policy.
-- Images live in shop-gallery/owner-catalog/<shop_slug>/...
-- -----------------------------------------------------------------
drop policy if exists "Owners can upload catalog images"
  on storage.objects;

create policy "Owners can upload catalog images"
on storage.objects
for insert
to authenticated
with check (
  bucket_id='shop-gallery'
  and (storage.foldername(name))[1]='owner-catalog'
  and public.owner_has_shop_option(
    (storage.foldername(name))[2],
    'catalog_enabled'
  )
  and public.owner_has_shop_option(
    (storage.foldername(name))[2],
    'catalog_images_enabled'
  )
);

drop policy if exists "Owners can delete catalog images"
  on storage.objects;

create policy "Owners can delete catalog images"
on storage.objects
for delete
to authenticated
using (
  bucket_id='shop-gallery'
  and (storage.foldername(name))[1]='owner-catalog'
  and exists (
    select 1
    from public.shop_owners o
    where o.user_id=(select auth.uid())
      and o.shop_slug=(storage.foldername(name))[2]
  )
);

-- -----------------------------------------------------------------
-- Realtime: one lightweight catalog-header row is the change signal.
-- Public module also watches shop_profiles for Admin ON/OFF.
-- -----------------------------------------------------------------
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname='supabase_realtime'
      and schemaname='public'
      and tablename='shop_catalogs'
  ) then
    alter publication supabase_realtime add table public.shop_catalogs;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname='supabase_realtime'
      and schemaname='public'
      and tablename='shop_profiles'
  ) then
    alter publication supabase_realtime add table public.shop_profiles;
  end if;
end;
$$;

comment on table public.shop_catalogs is
  'Optional ShoufHon shop catalog/menu header. Admin entitlement lives in shop_profiles.directory_options.';
comment on table public.shop_catalog_sections is
  'Swipeable Catalog/Menu sections for one shop.';
comment on table public.shop_catalog_items is
  'Catalog/Menu products or services with optional image and flexible price mode.';
comment on table public.shop_catalog_item_prices is
  'Multiple size/variant price options attached to a Catalog item.';
